// GENERATED by tool/sync_version.dart — do not edit.
// Run `dart run tool/sync_version.dart` after bumping `pubspec.yaml`.

/// Version of the `synheart_core` Flutter SDK package.
///
/// Kept in sync with the `version:` field in pubspec.yaml. Surfaced so host
/// apps can display the SDK version in About / diagnostics screens without
/// having to ship the lock file as an asset.
const String synheartCoreVersion = '0.14.0';
